recipes-containers/mkfs-hostapp-native: Use BBCLASSEXTEND instead of inherit native
This fixes the following error seen in Honister:
    ERROR: mkfs-hostapp-native-1.0-r0 do_prepare_recipe_sysroot:
        Manifest /work/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-linux-libc-headers.populate_sysroot not found in
        cortexa53 armv8a-crc armv8a aarch64 allarch x86_64_x86_64-nativesdk (variant '')?

Change-type: patch
Signed-off-by: Alexandru Costache <alexandru@balena.io>